version: '3.3'

services:
  git:
    image: alpine/git
    command: git clone https://github.com/patajones/redmine_prj_treeview.git /plugins/redmine_prj_treeview
    volumes:
      - /plugins:/plugins
      
  redmine:
    image: redmine:3.4.6
    environment:
      - "RAILS_ENV=development"
      - "REDMINE_PLUGINS_MIGRATE=yes"
    volumes:
      - /plugins:/usr/src/redmine/plugins
    ports:
      - "8000:3000"
